export const enterpriseCopy = {
  zh: {
    hero: {
      badge: "✨ Enterprise AI Transformation & Workflow Automation",
      headline: "強大、精準、可量化的企業級 AI 轉型解決方案",
      subheadline:
        "結合前阿里巴巴技術專家的大型系統架構經驗，與前國際投行高管的數位轉型視野。我們不講空言，專注於深入評估業務流程，為企業量身打造並 100% 落地部署 AI Agent 與自動化工作流，實質提升營運效益。",
      ctaPrimary: "預約 1-on-1 專家免費諮詢",
      ctaSecondary: "查看企業成功案例",
      metrics: [
        { value: "60%+", label: "平均節省人力重覆性工作時間" },
        { value: "100+", label: "企業自動化與 AI 項目落地經驗" },
        { value: "Zero Data Leak", label: "私有化數據隔離與金融級安全認證" },
        { value: "3-4 週", label: "從 POC 概念驗證到正式系統上線" },
      ],
    },
    value: {
      title: "突破傳統 IT 外包局限：頂尖技術架構 × 國際投行視野 × 高效敏捷落地",
      items: [
        {
          title: "頂尖雙領域專家親自帶隊 (Executive Leadership)",
          body: "由前阿里技術專家 Felix Zhu 主導系統架構，前投行聯席董事 Chris Lau 負責商業流程重構。沒有層層委外，由懂技術又懂商業的專家直接對接您的核心團隊。",
        },
        {
          title: "100% 客製化 Agent 與 API 系統整合 (Custom Tailored, No Templates)",
          body: "絕非套用市售通用 SaaS 工具。我們深入企業現有 ERP、CRM、Database 與溝通軟體（Slack/Teams/WhatsApp），打造專屬 AI Agent 工作流。",
        },
        {
          title: "金融級資安防護與私有化數據隔離 (Enterprise Data Security)",
          body: "嚴格遵守企業資料隱私規範。支援 Enterprise RAG 私有數據庫建置、地端私有化部署（On-Premises）或專屬 VPC 隔離，確保企業核心數據與 Prompt 絕不流向公有模型訓練。",
        },
        {
          title: "量化可追蹤的增效投資報酬率 (Quantifiable ROI Focus)",
          body: "每一項 AI 轉型專案均提供清晰的 ROI 評估報告。我們以「節省多少工時」、「降低多少出錯率」與「提升多少營收轉化」作為最終驗收標準。",
        },
      ],
    },
    servicesTitle: "四大核心服務項目",
    services: [
      {
        title: "客製化 AI Agent 系統開發 (Custom Autonomous AI Agents)",
        intro: "打造能理解複雜商業邏輯、能自主呼叫工具（Tool Calling）並跨系統執行任務的專屬 AI 代理。",
        scenesLabel: "適用場景",
        scenes: "24/7 智能客服與自動售前轉化Agent、企業內部知識庫助理（RAG）、財務發票自動審核Agent、自動化合規審查助理。",
        techLabel: "技術亮點",
        tech: "多 Agent 協作架構（Multi-Agent Swarm）、LLM 微調與 RAG 混合檢索、Model Context Protocol (MCP) 本地端 API 連線。",
      },
      {
        title: "RPA 與超自動化工作流重構 (RPA & Hyper-Automation)",
        intro: "消除企業內部無意義的重複性人工「搬運數據」與「跨頁面操作」，實現全自動端到端流程。",
        scenesLabel: "適用場景",
        scenes: "多平台訂單數據匯總與自動排單、跨系統 API 數據同步、跨國供應鏈對帳、自動化 PDF/Excel 報告生成與發送。",
        techLabel: "技術亮點",
        tech: "Python/Playwright 無頭瀏覽器自動化、無縫對接 Make/n8n/Zapier 與企業內部 Legacy 系統。",
      },
      {
        title: "數位轉型顧問與 AI 架構規劃 (Digital Transformation & Advisory)",
        intro: "針對擬定導入 AI 但缺乏清晰路線圖的企業，提供全方位的技術審計、ROI 評估與安全性規劃。",
        scenesLabel: "適用場景",
        scenes: "企業現有 IT 架構 AI 化評估、AI 工具鏈選擇與成本控制、系統安全性與資料隱私審計、轉型 Roadmap 制定。",
        techLabel: "交付物",
        tech: "完整《企業 AI 轉型技術可行性報告》、《系統架構藍圖》與《ROI 預估分析表》。",
      },
      {
        title: "企業團隊 Vibe Coding & AI 賦能工作坊 (Corporate AI Enablement Workshops)",
        intro: "提升企業內部員工與 IT 團隊的 AI 應用能力，將 Vibe Coding 與 AI Agent 開發流深度注入日常運營。",
        scenesLabel: "適用場景",
        scenes: "非技術部門（HR/Marketing/Sales）AI 自動化工作流培訓、IT 團隊 Cursor/Claude 敏捷開發培訓。",
        techLabel: "培訓特色",
        tech: "100% 結合企業真實業務案例做實作演練，課後提供獨家 SOP 手冊與 30 天導師在線答疑。",
      },
    ],
    process: {
      title: "清晰透明的 5 步交付流程，確保專案 100% 按時高質上線",
      steps: [
        {
          num: "01",
          title: "商業痛點診斷與工作流審計 (Audit & Discovery)",
          body: "專家團隊深入了解企業現有業務流程，找出耗費最多人力、最易出錯的瓶頸節點，評估 AI 導入可行性。",
        },
        {
          num: "02",
          title: "POC 概念驗證與 ROI 架構方案 (POC & Architecture Design)",
          body: "1-2 週內快速打造 Prototype (POC)，實測 AI 準確度與可行性，並提供精確的系統架構規劃與 ROI 預算報告。",
        },
        {
          num: "03",
          title: "客製化研發與 API/Agent 串接 (Custom Engineering)",
          body: "進行生產環境級別的程式碼開發、Prompt 調校、RAG 向量庫構建與企業原有系統（CRM/ERP/Database）串接。",
        },
        {
          num: "04",
          title: "UAT 嚴格驗收與私有化部署 (UAT & Secure Deployment)",
          body: "進行跨場景測試與壓力測試（UAT），確保安全性與穩定度後，於企業私有雲或指定 VPC 環境完成部署。",
        },
        {
          num: "05",
          title: "團隊操作培訓與長期維運 (Enablement & Continuous Optimization)",
          body: "舉辦內部員工操作工作坊，交付系統使用文案與 API 說明文件，並提供後續系統維護與模型優化支援。",
        },
      ],
    },
    cases: {
      title: "真實企業轉型案例：看我們如何協助客戶實現數據驅動的爆發性成長",
      items: [
        {
          title: "100 人規模中型企業 —— HR 與招聘流程全自動化 Agent 改造",
          backgroundLabel: "客戶背景",
          background: "港資中型服務業企業，每月需處理上千份履歷與頻繁的員工 Onboarding 流程。",
          painLabel: "面臨痛點",
          pain: "HR 團隊每天花費超過 4 小時手動篩選履歷、安排面試時間及填寫內部 HR 系統，效率低下。",
          solutionLabel: "解決方案",
          solutions: [
            "打造專屬 HR Recruiting Agent，自動解析多平台 PDF 履歷並依職位需求精準評分。",
            "串接 Outlook/Google Calendar 與 WhatsApp API，由 Agent 自動對接候選人進行初篩問答與面試排程。",
            "整合 Supabase 與內部 HR 系統，自動完成錄取通知書生成與入職資料彙整。",
          ],
          resultLabel: "量化成效",
          result: "招聘篩選時間縮短 80%，HR 團隊每月節省 120+ 小時 人力成本，候選人回覆速度提升 5 倍。",
        },
        {
          title: "年 GMV 數千萬跨境電商 —— 供應鏈排單、發票對帳與智能售後 Agent",
          backgroundLabel: "客戶背景",
          background: "知名跨境電商品牌，營運覆蓋 Amazon、Shopify 與多個東南亞平台。",
          painLabel: "面臨痛點",
          pain: "每日數千筆訂單數據分散於各平台，跨國供應鏈對帳極易出錯，客服響應慢導致退單率偏高。",
          solutionLabel: "解決方案",
          solutions: [
            "部署 E-commerce Operations Automation Workflow，自動抓取各平台 API 訂單數據並匯總至中央數據庫。",
            "建立 RPA 發票與對帳 Agent，自動識別供應商 PDF 帳單並與銀行流水進行比對。",
            "串接 多語種 AI 客服 Agent，精準處理訂單查詢、物流追蹤與簡單退換貨請求。",
          ],
          resultLabel: "量化成效",
          result: "對帳零出錯率，客服人力成本降低 65%，訂單處理效率提升 300%，年節省運營成本數十萬港幣。",
        },
        {
          title: "知名金融顧問機構 —— 合規文件審查與自動化報告生成系統",
          backgroundLabel: "客戶背景",
          background: "專注於併購與資產管理的專業金融顧問公司。",
          painLabel: "面臨痛點",
          pain: "分析師需閱讀數百頁的法律文件與財務報表，撰寫 Due Diligence 報告耗時且風險極高。",
          solutionLabel: "解決方案",
          solutions: [
            "建置 Enterprise RAG 私有金融知識庫，對所有歷史文件與法規進行加密向量化儲存。",
            "開發 Due Diligence Assistant Agent，能在 30 秒內精準提取合同關鍵條款、潛在法律風險與財務異常點。",
            "自動生成符合監管標準的初稿報告，並附帶原文出處標註供分析師複查。",
          ],
          resultLabel: "量化成效",
          result: "分析師文件審閱速度提升 10 倍，DD 報告撰寫時間從 3 天縮短至 2 小時，大幅提升併購案處理量。",
        },
      ],
    },
    booking: {
      formTitle: "預約專家免費 1-on-1 AI 轉型諮詢",
      formSubtitle: "填寫您的企業需求，我們的 AI 轉型專家將於 24 小時內與您聯繫，並提供初步技術評估。",
      company: "公司名稱 (Company Name)",
      contact: "聯絡人姓名 (Contact Name)",
      email: "企業 Email (Business Email)",
      phone: "聯絡電話 (Phone Number)",
      service: "服務需求 (Service Required)",
      budget: "預估專案預算 (Estimated Budget)",
      brief: "業務痛點與預期目標 (Project Brief)",
      submit: "送出諮詢申請",
      submitting: "送出中…",
      successTitle: "已收到你的諮詢申請",
      successBody: "我們會在 24 小時內與你聯絡，並提供初步技術評估。",
      noService: "請至少選擇一項服務需求",
    },
  },
  en: {
    hero: {
      badge: "✨ Enterprise AI Transformation & Workflow Automation",
      headline: "Powerful, precise, measurable enterprise AI transformation",
      subheadline:
        "Combining large-scale systems architecture from former Alibaba technical specialists with the digital-transformation perspective of former international investment-banking executives. We skip empty talk. We assess operating workflows in depth, then design and fully deploy custom AI agents and automation — live in production — to raise real operating performance.",
      ctaPrimary: "Book a free 1-on-1 expert consultation",
      ctaSecondary: "See enterprise case studies",
      metrics: [
        { value: "60%+", label: "Average time saved on repetitive work" },
        { value: "100+", label: "Enterprise automation and AI programmes shipped" },
        { value: "Zero Data Leak", label: "Private data isolation and finance-grade security" },
        { value: "3-4 weeks", label: "From POC to a production system" },
      ],
    },
    value: {
      title: "Beyond traditional IT outsourcing: elite architecture × global IB perspective × fast, disciplined delivery",
      items: [
        {
          title: "Led by dual-domain specialists (Executive Leadership)",
          body: "Former Alibaba specialist Felix Zhu leads system architecture; former investment-banking executive director Chris Lau leads process redesign. No layered outsourcing — technical and commercial operators work directly with your core team.",
        },
        {
          title: "100% custom agents and API integration (Custom Tailored, No Templates)",
          body: "Not a generic SaaS wrapper. We go into your ERP, CRM, databases, and collaboration tools (Slack / Teams / WhatsApp) and build dedicated AI agent workflows.",
        },
        {
          title: "Finance-grade security and private data isolation (Enterprise Data Security)",
          body: "We follow enterprise privacy rules. Enterprise RAG on private data, on-premises deployment, or a dedicated VPC — core data and prompts never go into public-model training.",
        },
        {
          title: "Quantifiable ROI you can track (Quantifiable ROI Focus)",
          body: "Every programme includes a clear ROI report. We accept work against hours saved, error-rate reduction, and conversion lift.",
        },
      ],
    },
    servicesTitle: "Four core services",
    services: [
      {
        title: "Custom AI agent systems (Custom Autonomous AI Agents)",
        intro: "Agents that understand complex commercial logic, call tools, and execute work across systems.",
        scenesLabel: "Where it fits",
        scenes: "24/7 sales and support agents, internal knowledge assistants (RAG), invoice-review agents, and compliance assistants.",
        techLabel: "Technical notes",
        tech: "Multi-agent collaboration, LLM fine-tuning with hybrid RAG, and Model Context Protocol (MCP) for local API access.",
      },
      {
        title: "RPA and hyper-automation (RPA & Hyper-Automation)",
        intro: "Remove pointless data-moving and cross-page clicking so the process runs end to end.",
        scenesLabel: "Where it fits",
        scenes: "Multi-platform order intake and dispatch, cross-system API sync, cross-border supply-chain reconciliation, and automated PDF / Excel reporting.",
        techLabel: "Technical notes",
        tech: "Python / Playwright headless automation, plus Make / n8n / Zapier and legacy system connections.",
      },
      {
        title: "Digital transformation and AI architecture (Digital Transformation & Advisory)",
        intro: "For companies that want AI but lack a route map: technical audit, ROI, and security planning.",
        scenesLabel: "Where it fits",
        scenes: "AI-readiness of the current IT stack, tool-chain and cost control, security and privacy audit, and a transformation roadmap.",
        techLabel: "Deliverables",
        tech: "A full AI feasibility report, system-architecture blueprint, and ROI estimate.",
      },
      {
        title: "Team vibe-coding and AI enablement workshops (Corporate AI Enablement Workshops)",
        intro: "Raise internal AI capability so vibe coding and agents become part of daily operations.",
        scenesLabel: "Where it fits",
        scenes: "Non-technical teams (HR / Marketing / Sales) on automation workflows; IT teams on Cursor / Claude delivery.",
        techLabel: "Workshop notes",
        tech: "Exercises on your real work, exclusive SOP manuals, and 30 days of mentor Q&A after class.",
      },
    ],
    process: {
      title: "A clear 5-step delivery path so the programme ships on time and at quality",
      steps: [
        {
          num: "01",
          title: "Business-pain diagnosis and workflow audit (Audit & Discovery)",
          body: "We map current operations, find the most expensive and error-prone bottlenecks, and judge whether AI belongs there.",
        },
        {
          num: "02",
          title: "POC and ROI architecture (POC & Architecture Design)",
          body: "A prototype in 1–2 weeks to test accuracy and feasibility, plus a precise architecture plan and ROI budget.",
        },
        {
          num: "03",
          title: "Custom build and API / agent integration (Custom Engineering)",
          body: "Production-grade code, prompt tuning, RAG stores, and connections into your CRM / ERP / databases.",
        },
        {
          num: "04",
          title: "UAT and private deployment (UAT & Secure Deployment)",
          body: "Cross-scenario and stress tests, then deploy into your private cloud or designated VPC.",
        },
        {
          num: "05",
          title: "Team training and ongoing operations (Enablement & Continuous Optimization)",
          body: "Internal workshops, usage notes and API docs, plus maintenance and model-optimization support.",
        },
      ],
    },
    cases: {
      title: "Live transformation work: how we help clients grow from their own data",
      items: [
        {
          title: "Mid-size firm (~100 people) — HR and recruiting agents",
          backgroundLabel: "Client",
          background: "A Hong Kong-capital mid-size services firm handling thousands of CVs and frequent onboarding each month.",
          painLabel: "Pain",
          pain: "HR spent more than four hours a day screening CVs, booking interviews, and filling the internal HR system.",
          solutionLabel: "What we built",
          solutions: [
            "A dedicated recruiting agent that parses multi-platform PDF CVs and scores them against the role.",
            "Outlook / Google Calendar and WhatsApp API so the agent can screen candidates and book interviews.",
            "Supabase plus the internal HR system so offer letters and onboarding packs assemble automatically.",
          ],
          resultLabel: "Result",
          result: "Screening time down 80%, 120+ HR hours saved each month, candidate reply speed up 5×.",
        },
        {
          title: "Cross-border e-commerce (tens of millions in GMV) — dispatch, invoices, after-sales",
          backgroundLabel: "Client",
          background: "A known cross-border brand on Amazon, Shopify, and several Southeast Asian platforms.",
          painLabel: "Pain",
          pain: "Thousands of daily orders split across platforms, cross-border reconciliation errors, and slow support that raised refunds.",
          solutionLabel: "What we built",
          solutions: [
            "An operations workflow that pulls platform APIs into one database.",
            "An RPA invoice agent that reads supplier PDFs and matches them to bank lines.",
            "A multilingual support agent for order queries, tracking, and simple returns.",
          ],
          resultLabel: "Result",
          result: "Zero reconciliation errors, support cost down 65%, order handling up 300%, hundreds of thousands of HKD saved per year.",
        },
        {
          title: "Financial advisory firm — compliance review and automated reports",
          backgroundLabel: "Client",
          background: "A professional advisory firm focused on M&A and asset management.",
          painLabel: "Pain",
          pain: "Analysts read hundreds of pages of legal and financial documents; due-diligence reports were slow and high-risk.",
          solutionLabel: "What we built",
          solutions: [
            "An enterprise RAG store of historical files and regulations, encrypted and vectorised.",
            "A due-diligence assistant that extracts key clauses, legal risk, and financial anomalies in about 30 seconds.",
            "First-draft reports to regulatory standard, with source citations for analyst review.",
          ],
          resultLabel: "Result",
          result: "Document review 10× faster; DD drafts from 3 days to 2 hours; higher deal throughput.",
        },
      ],
    },
    booking: {
      formTitle: "Book a free 1-on-1 AI transformation consultation",
      formSubtitle: "Tell us the brief. Our team will contact you within 24 hours with an initial technical assessment.",
      company: "Company Name",
      contact: "Contact Name",
      email: "Business Email",
      phone: "Phone Number",
      service: "Service Required",
      budget: "Estimated Budget",
      brief: "Project Brief",
      submit: "Submit enquiry",
      submitting: "Submitting…",
      successTitle: "We received your enquiry",
      successBody: "We will contact you within 24 hours with an initial technical assessment.",
      noService: "Please choose at least one service.",
    },
  },
} as const;
